### ISSUE TITLE
alienware-kbl launcher not working over Linux Mint

### ISSUE THREAD

**Issue by xion87** [rsm-imap-cc/alienware-kbl#4]

**Comment by rsm-imap-cc** [comment]
Hi xion87, thank you for reporting this.

Could you be more specific? I Actually does not understand the problem

**Comment by xion87** [comment]
Well if i click Alienware Keyboard LIghts, (after the installation by adding it as resource and update it) it ask the passworld, and nothing happen after i confirm it, i am using linux mint 17.1 rebecca mate 64 bit

**Comment by rsm-imap-cc** [comment]
So:
 > You installed the program from the repository, you made an update, and when you use the  icon of the launcher (from some applications menu), it asks your password, and then nothing happends. I'm alright?

I may know the problem. I'll correct it for the new version that will be become maybe even today.

It would be nice if you can try this:

> open a terminal and become root: sudo su
> launch alienware-kbl: setsid alienware-kbl

the program should work! It is only the launcher by using gksu that fails on mint I think

**Comment by xion87** [comment]
it work perfect by using your commands:
open a terminal and become root: sudo su
launch alienware-kbl: setsid alienware-kbl

I find also a typo error 
right = it turn colours on left 
left = it turn colours on right

cheer!

**Comment by xion87** [comment]
I noticed also if i try to start the software by using setsid alienware-kbl , it ask the password and nothig happen (exactly like when i click the icon), but i i launch it with sudo it work... .hope that it help you

**Comment by rsm-imap-cc** [comment]
I've fixed the problems on 1.3.8~7 ! Thanks so much for repoting this, the launcher was working in my distribution so it would have took me a lot of time to find about it !

As for the:

I find also a typo error
right = it turn colours on left
left = it turn colours on right

This may be a bug of the M17xR3 configuration, but I dont really know. I fixed that bug some time ago and it works good on my computer. If you want me to repair it please open a new bug, so we can talk about it an try to fix it for the M17xR3 computers. ( I may need you to do multiple tests/trys )
